package eu.sim642.adventofcode2024

import Day8._
import org.scalatest.funsuite.AnyFunSuite

class Day8Test extends AnyFunSuite {

  val exampleInput =
    """............
      |........0...
      |.....0......
      |.......0....
      |....0.......
      |......A.....
      |............
      |............
      |........A...
      |.........A..
      |............
      |............""".stripMargin

  val exampleInput2 =
    """T.........
      |...T......
      |.T........
      |..........
      |..........
      |..........
      |..........
      |..........
      |..........
      |..........""".stripMargin

  test("Part 1 examples") {
    assert(Part1.countAntinodes(parseGrid(exampleInput)) == 14)
  }

  test("Part 1 input answer") {
    assert(Part1.countAntinodes(parseGrid(input)) == 357)
  }

  test("Part 2 examples") {
    assert(Part2.countAntinodes(parseGrid(exampleInput2)) == 9)
    assert(Part2.countAntinodes(parseGrid(exampleInput)) == 34)
  }

  test("Part 2 input answer") {
    assert(Part2.countAntinodes(parseGrid(input)) == 1266)
  }
}
