package eu.sim642.adventofcode2025

import Day7._
import org.scalatest.funsuite.AnyFunSuite

class Day7Test extends AnyFunSuite {

  val exampleInput =
    """.......S.......
      |...............
      |.......^.......
      |...............
      |......^.^......
      |...............
      |.....^.^.^.....
      |...............
      |....^.^...^....
      |...............
      |...^.^...^.^...
      |...............
      |..^...^.....^..
      |...............
      |.^.^.^.^.^...^.
      |...............""".stripMargin

  test("Part 1 examples") {
    assert(countBeamSplits(parseGrid(exampleInput)) == 21)
  }

  test("Part 1 input answer") {
    assert(countBeamSplits(parseGrid(input)) == 1587)
  }

  test("Part 2 examples") {
    assert(countTimelines(parseGrid(exampleInput)) == 40)
  }

  test("Part 2 input answer") {
    assert(countTimelines(parseGrid(input)) == 5748679033029L)
  }
}
