package eu.sim642.adventofcode2025

import Day7._
import org.scalatest.funsuite.AnyFunSuite

class Day7Test extends AnyFunSuite {

  val exampleInput =
    """.......S.......
      |...............
      |.......^.......
      |...............
      |......^.^......
      |...............
      |.....^.^.^.....
      |...............
      |....^.^...^....
      |...............
      |...^.^...^.^...
      |...............
      |..^...^.....^..
      |...............
      |.^.^.^.^.^...^.
      |...............""".stripMargin

  test("Part 1 examples") {
    assert(countBeamSplits(parseGrid(exampleInput)) == 21)
  }

  test("Part 1 input answer") {
    assert(countBeamSplits(parseGrid(input)) == 1587)
  }
}
